// IIntegrationAdapter.cs
// Core adapter interface for all 12 third-party integrations.
// The Integration Orchestrator only knows this contract — never the concrete system.
// Adding a new integration = implementing this interface + registering it. Zero core changes.

using System.Threading;
using System.Threading.Tasks;

namespace EllucianIntegrationEngine.Adapters;

/// <summary>
/// Defines the contract every third-party integration adapter must fulfill.
/// The orchestration layer dispatches work through this interface exclusively,
/// ensuring retry logic, tracing, and tenant isolation apply uniformly
/// regardless of which system is being called.
/// </summary>
public interface IIntegrationAdapter
{
    /// <summary>
    /// A stable identifier for this adapter, used in telemetry span names,
    /// retry policy lookups, and Dead Letter Queue routing context.
    /// Example: "financial-aid-platform", "payment-processor"
    /// </summary>
    string AdapterName { get; }

    /// <summary>
    /// Executes the integration request against the third-party system.
    /// The orchestrator calls this inside the retry ladder; implementations
    /// should be stateless and idempotent where possible.
    /// </summary>
    /// <param name="request">
    ///   Typed request payload. Includes the IdempotencyKey derived from
    ///   the originating OutboxMessage.Id, used to detect and reject duplicates
    ///   on the remote system where supported.
    /// </param>
    /// <param name="tenantContext">
    ///   Runtime-resolved tenant configuration. Carries the institution's
    ///   API credentials, endpoint overrides, feature flags, and timeout settings.
    ///   Never hardcode credentials — always pull from tenantContext.
    /// </param>
    /// <param name="cancellationToken">Propagated from the outer HTTP request context.</param>
    /// <returns>
    ///   <see cref="AdapterResult"/> indicating success, retriable failure, or
    ///   terminal failure. The orchestrator uses the result type to decide
    ///   whether to retry, DLQ-route, or acknowledge the message.
    /// </returns>
    Task<AdapterResult> ExecuteAsync(
        IntegrationRequest request,
        TenantContext tenantContext,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Structured result from an adapter execution. Avoids exception-as-control-flow
/// for expected failure modes (rate limits, transient errors, permanent rejections).
/// </summary>
public sealed record AdapterResult
{
    public bool IsSuccess { get; init; }

    /// <summary>
    /// If false, the orchestrator will apply the next retry delay and try again.
    /// If true, the message is routed to the DLQ immediately with this result attached.
    /// </summary>
    public bool IsTerminalFailure { get; init; }

    public string? ErrorCode { get; init; }
    public string? ErrorMessage { get; init; }
    public object? Payload { get; init; }

    public static AdapterResult Success(object? payload = null) =>
        new() { IsSuccess = true, Payload = payload };

    public static AdapterResult TransientFailure(string errorCode, string message) =>
        new() { IsSuccess = false, IsTerminalFailure = false, ErrorCode = errorCode, ErrorMessage = message };

    public static AdapterResult TerminalFailure(string errorCode, string message) =>
        new() { IsSuccess = false, IsTerminalFailure = true, ErrorCode = errorCode, ErrorMessage = message };
}

/// <summary>
/// Represents the work to be done by an adapter. The IdempotencyKey is
/// set by the OutboxPublisher from the originating transaction ID —
/// it is never generated by the adapter itself.
/// </summary>
public sealed record IntegrationRequest
{
    public required string IdempotencyKey { get; init; }
    public required string OperationType { get; init; }
    public required object Payload { get; init; }
    public DateTimeOffset CreatedAt { get; init; } = DateTimeOffset.UtcNow;
}
